### ISSUE TITLE
questions about flickerfreeprint

### ISSUE THREAD

**Issue by BastiaanMDC** [KrisKasprzak/FlickerFreePrint#1]
Hi Kris, I am having problems with your library for all other variables it works fine. except mine.

so ill explain. I am getting from MAX31855 values that are double formats and
i am doing the following:

      Data1.print(j,2); //slow down the speed of refresh
      sprintf(str,"TempEmag: %lu",c[0]);
      Data1.print(str);

it shows on the screen a up counter which isnt exactly a Temperature value.

could you help me with that?

best regards

Bastiaan

**Comment by KrisKasprzak** [comment]
I just tested this and works fine using this code

/*
Teensy 3.2TFT LCD 2.8" 320 x 240ILI9341 driver
Connections
MCU     LCD9       DC10      CS12      MISO11      MOSI13      SCK3v3     VCCGND     GND

 */#include <ILI9341_t3.h>           // fast display driver lib#include <FlickerFreePrint.h>     // library to draw w/o flicker#include <font_Arial.h>           // custom fonts for the ILI9341_t3.h
// some defines for pins#define TFT_CS        10#define TFT_DC        9
// simulating data coming from sensordouble ARRAY_TC_HOT[1] = {0.37980673};
// create the display objectILI9341_t3 Display(TFT_CS, TFT_DC);
FlickerFreePrint<ILI9341_t3> Data1(&Display, 65535, 0);
char str[30];
void setup() {
  Serial.begin(9600);
  Display.begin();  Display.setRotation(1);  Display.fillScreen(0);
  Display.setFont(Arial_48); // lets use giant font}
void loop() {
  Display.setCursor(0, 70);  // simulate temp changing  ARRAY_TC_HOT[0] += 0.01;  dtostrf(ARRAY_TC_HOT[0], sizeof(ARRAY_TC_HOT[0]), 2, str);  Data1.print(str);  delay(50);
}


Thanks,
Kris Kasprzak
 

    On Wednesday, September 16, 2020, 06:40:43 AM CDT, BastiaanMDC <notifications@github.com> wrote:  
 
 


Hi Kris, I am having problems with your library for all other variables it works fine. except mine.

so ill explain. I am getting from MAX31855 values that are double formats and
i am doing the following:

dtostrf(ARRAY_TC_HOT[0],sizeof(ARRAY_TC_HOT[0]),2,str);
Data1.print(str);

screen freezes over.... why is that?

if Serial.println(ARRAY_TC_HOT[0]) I neatly get my temperature value, I dont understand.

i tried this also in combination with the Sprintf command

best regards

Bastiaan

**Comment by BastiaanMDC** [comment]
Your code is fine, forgot to cancel the issue.

I am having problems with 5 devices on SPI.

The 4x Max31855 And a featherwing. I tried examples to let the record the four max31855s first and check with a digitalread if the Pin went high. But I can only access or the display without the temperature data or just a frozen display. Is there a simple way around two SPI devices putting data on the screen?

I posted similar questions on PJRC.
I am in the train now, and thanks for your time!

Best regards

Bastiaan

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Kris Kasprzak <notifications@github.com>
Verzonden: woensdag, september 16, 2020 3:26 PM
Aan: KrisKasprzak/FlickerFreePrint
CC: BastiaanMDC; Author
Onderwerp: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)


I just tested this and works fine using this code

/*
Teensy 3.2TFT LCD 2.8" 320 x 240ILI9341 driver
Connections
MCU     LCD9       DC10      CS12      MISO11      MOSI13      SCK3v3     VCCGND     GND

 */#include <ILI9341_t3.h>           // fast display driver lib#include <FlickerFreePrint.h>     // library to draw w/o flicker#include <font_Arial.h>           // custom fonts for the ILI9341_t3.h
// some defines for pins#define TFT_CS        10#define TFT_DC        9
// simulating data coming from sensordouble ARRAY_TC_HOT[1] = {0.37980673};
// create the display objectILI9341_t3 Display(TFT_CS, TFT_DC);
FlickerFreePrint<ILI9341_t3> Data1(&Display, 65535, 0);
char str[30];
void setup() {
  Serial.begin(9600);
  Display.begin();  Display.setRotation(1);  Display.fillScreen(0);
  Display.setFont(Arial_48); // lets use giant font}
void loop() {
  Display.setCursor(0, 70);  // simulate temp changing  ARRAY_TC_HOT[0] += 0.01;  dtostrf(ARRAY_TC_HOT[0], sizeof(ARRAY_TC_HOT[0]), 2, str);  Data1.print(str);  delay(50);
}


Thanks,
Kris Kasprzak


On Wednesday, September 16, 2020, 06:40:43 AM CDT, BastiaanMDC <notifications@github.com> wrote:




Hi Kris, I am having problems with your library for all other variables it works fine. except mine.

so ill explain. I am getting from MAX31855 values that are double formats and
i am doing the following:

dtostrf(ARRAY_TC_HOT[0],sizeof(ARRAY_TC_HOT[0]),2,str);
Data1.print(str);

screen freezes over.... why is that?

if Serial.println(ARRAY_TC_HOT[0]) I neatly get my temperature value, I dont understand.

i tried this also in combination with the Sprintf command

best regards

Bastiaan

**Comment by KrisKasprzak** [comment]
a wiring diagram would do wonders here. There are some pins that can't be used for chip selects but hard to diagnose with what's been given.
Thanks,
Kris Kasprzakkris.kasprzak@yahoo.com
 

    On Wednesday, September 16, 2020, 08:33:18 AM CDT, BastiaanMDC <notifications@github.com> wrote:  
 
 

Your code is fine, forgot to cancel the issue.

I am having problems with 5 devices on SPI.

The 4x Max31855 And a featherwing. I tried examples to let the record the four max31855s first and check with a digitalread if the Pin went high. But I can only access or the display without the temperature data or just a frozen display. Is there a simple way around two SPI devices putting data on the screen?

I posted similar questions on PJRC.
I am in the train now, and thanks for your time!

Best regards

Bastiaan

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Kris Kasprzak <notifications@github.com>
Verzonden: woensdag, september 16, 2020 3:26 PM
Aan: KrisKasprzak/FlickerFreePrint
CC: BastiaanMDC; Author
Onderwerp: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)


I just tested this and works fine using this code

/*
Teensy 3.2TFT LCD 2.8" 320 x 240ILI9341 driver
Connections
MCU LCD9 DC10 CS12 MISO11 MOSI13 SCK3v3 VCCGND GND

 */#include <ILI9341_t3.h> // fast display driver lib#include <FlickerFreePrint.h> // library to draw w/o flicker#include <font_Arial.h> // custom fonts for the ILI9341_t3.h
// some defines for pins#define TFT_CS 10#define TFT_DC 9
// simulating data coming from sensordouble ARRAY_TC_HOT[1] = {0.37980673};
// create the display objectILI9341_t3 Display(TFT_CS, TFT_DC);
FlickerFreePrint<ILI9341_t3> Data1(&Display, 65535, 0);
char str[30];
void setup() {
 Serial.begin(9600);
 Display.begin(); Display.setRotation(1); Display.fillScreen(0);
 Display.setFont(Arial_48); // lets use giant font}
void loop() {
 Display.setCursor(0, 70); // simulate temp changing ARRAY_TC_HOT[0] += 0.01; dtostrf(ARRAY_TC_HOT[0], sizeof(ARRAY_TC_HOT[0]), 2, str); Data1.print(str); delay(50);
}


Thanks,
Kris Kasprzak


On Wednesday, September 16, 2020, 06:40:43 AM CDT, BastiaanMDC <notifications@github.com> wrote:




Hi Kris, I am having problems with your library for all other variables it works fine. except mine.

so ill explain. I am getting from MAX31855 values that are double formats and
i am doing the following:

dtostrf(ARRAY_TC_HOT[0],sizeof(ARRAY_TC_HOT[0]),2,str);
Data1.print(str);

screen freezes over.... why is that?

if Serial.println(ARRAY_TC_HOT[0]) I neatly get my temperature value, I dont understand.

i tried this also in combination with the Sprintf command

best regards

Bastiaan

**Comment by BastiaanMDC** [comment]
Hi Kris,

Its clearly a bus access problem. Was wondering if this could be daisy chained.

Here is the link to the forum.
https://forum.pjrc.com/threads/62947-max31855-question-calibration-not-seeing-it

The featherwing and max31855 has the pins on:


define MAXCLK 13 //max31855 nothing else.
#define MAXDO   9  //MISO required for the MAX31855
#define TFT_DC  10
#define TFT_CS 8
#define TFT_RST -1

Mosi and miso are also used on pins 11,12 for the tft.

The boards I am using:
https://www.digikey.de/catalog/de/partgroup/max31855-pmodtc1-development-board/53250

Featherwing 3.5”
https://forum.pjrc.com/threads/61858-problems-HX8357?highlight=Featherwing



________________________________
Van: Kris Kasprzak <notifications@github.com>
Verzonden: woensdag, september 16, 2020 4:02 PM
Aan: KrisKasprzak/FlickerFreePrint
CC: BastiaanMDC; Author
Onderwerp: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)


a wiring diagram would do wonders here. There are some pins that can't be used for chip selects but hard to diagnose with what's been given.
Thanks,
Kris Kasprzakkris.kasprzak@yahoo.com


On Wednesday, September 16, 2020, 08:33:18 AM CDT, BastiaanMDC <notifications@github.com> wrote:



Your code is fine, forgot to cancel the issue.

I am having problems with 5 devices on SPI.

The 4x Max31855 And a featherwing. I tried examples to let the record the four max31855s first and check with a digitalread if the Pin went high. But I can only access or the display without the temperature data or just a frozen display. Is there a simple way around two SPI devices putting data on the screen?

I posted similar questions on PJRC.
I am in the train now, and thanks for your time!

Best regards

Bastiaan

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Kris Kasprzak <notifications@github.com>
Verzonden: woensdag, september 16, 2020 3:26 PM
Aan: KrisKasprzak/FlickerFreePrint
CC: BastiaanMDC; Author
Onderwerp: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)


I just tested this and works fine using this code

/*
Teensy 3.2TFT LCD 2.8" 320 x 240ILI9341 driver
Connections
MCU LCD9 DC10 CS12 MISO11 MOSI13 SCK3v3 VCCGND GND

*/#include <ILI9341_t3.h> // fast display driver lib#include <FlickerFreePrint.h> // library to draw w/o flicker#include <font_Arial.h> // custom fonts for the ILI9341_t3.h
// some defines for pins#define TFT_CS 10#define TFT_DC 9
// simulating data coming from sensordouble ARRAY_TC_HOT[1] = {0.37980673};
// create the display objectILI9341_t3 Display(TFT_CS, TFT_DC);
FlickerFreePrint<ILI9341_t3> Data1(&Display, 65535, 0);
char str[30];
void setup() {
Serial.begin(9600);
Display.begin(); Display.setRotation(1); Display.fillScreen(0);
Display.setFont(Arial_48); // lets use giant font}
void loop() {
Display.setCursor(0, 70); // simulate temp changing ARRAY_TC_HOT[0] += 0.01; dtostrf(ARRAY_TC_HOT[0], sizeof(ARRAY_TC_HOT[0]), 2, str); Data1.print(str); delay(50);
}


Thanks,
Kris Kasprzak


On Wednesday, September 16, 2020, 06:40:43 AM CDT, BastiaanMDC <notifications@github.com> wrote:




Hi Kris, I am having problems with your library for all other variables it works fine. except mine.

so ill explain. I am getting from MAX31855 values that are double formats and
i am doing the following:

dtostrf(ARRAY_TC_HOT[0],sizeof(ARRAY_TC_HOT[0]),2,str);
Data1.print(str);

screen freezes over.... why is that?

if Serial.println(ARRAY_TC_HOT[0]) I neatly get my temperature value, I dont understand.

i tried this also in combination with the Sprintf command

best regards

Bastiaan

**Comment by BastiaanMDC** [comment]
Many thanks

Bastiaan

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: bastiaan.pierik@mdc-berlin.de
Verzonden: woensdag, september 16, 2020 4:51 PM
Aan: KrisKasprzak/FlickerFreePrint
Onderwerp: Re: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)

Hi Kris,

Its clearly a bus access problem. Was wondering if this could be daisy chained.

Here is the link to the forum.
https://forum.pjrc.com/threads/62947-max31855-question-calibration-not-seeing-it

The featherwing and max31855 has the pins on:


define MAXCLK 13 //max31855 nothing else.
#define MAXDO   9  //MISO required for the MAX31855
#define TFT_DC  10
#define TFT_CS 8
#define TFT_RST -1

Mosi and miso are also used on pins 11,12 for the tft.

The boards I am using:
https://www.digikey.de/catalog/de/partgroup/max31855-pmodtc1-development-board/53250

Featherwing 3.5”
https://forum.pjrc.com/threads/61858-problems-HX8357?highlight=Featherwing



________________________________
Van: Kris Kasprzak <notifications@github.com>
Verzonden: woensdag, september 16, 2020 4:02 PM
Aan: KrisKasprzak/FlickerFreePrint
CC: BastiaanMDC; Author
Onderwerp: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)


a wiring diagram would do wonders here. There are some pins that can't be used for chip selects but hard to diagnose with what's been given.
Thanks,
Kris Kasprzakkris.kasprzak@yahoo.com


On Wednesday, September 16, 2020, 08:33:18 AM CDT, BastiaanMDC <notifications@github.com> wrote:



Your code is fine, forgot to cancel the issue.

I am having problems with 5 devices on SPI.

The 4x Max31855 And a featherwing. I tried examples to let the record the four max31855s first and check with a digitalread if the Pin went high. But I can only access or the display without the temperature data or just a frozen display. Is there a simple way around two SPI devices putting data on the screen?

I posted similar questions on PJRC.
I am in the train now, and thanks for your time!

Best regards

Bastiaan

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Kris Kasprzak <notifications@github.com>
Verzonden: woensdag, september 16, 2020 3:26 PM
Aan: KrisKasprzak/FlickerFreePrint
CC: BastiaanMDC; Author
Onderwerp: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)


I just tested this and works fine using this code

/*
Teensy 3.2TFT LCD 2.8" 320 x 240ILI9341 driver
Connections
MCU LCD9 DC10 CS12 MISO11 MOSI13 SCK3v3 VCCGND GND

*/#include <ILI9341_t3.h> // fast display driver lib#include <FlickerFreePrint.h> // library to draw w/o flicker#include <font_Arial.h> // custom fonts for the ILI9341_t3.h
// some defines for pins#define TFT_CS 10#define TFT_DC 9
// simulating data coming from sensordouble ARRAY_TC_HOT[1] = {0.37980673};
// create the display objectILI9341_t3 Display(TFT_CS, TFT_DC);
FlickerFreePrint<ILI9341_t3> Data1(&Display, 65535, 0);
char str[30];
void setup() {
Serial.begin(9600);
Display.begin(); Display.setRotation(1); Display.fillScreen(0);
Display.setFont(Arial_48); // lets use giant font}
void loop() {
Display.setCursor(0, 70); // simulate temp changing ARRAY_TC_HOT[0] += 0.01; dtostrf(ARRAY_TC_HOT[0], sizeof(ARRAY_TC_HOT[0]), 2, str); Data1.print(str); delay(50);
}


Thanks,
Kris Kasprzak


On Wednesday, September 16, 2020, 06:40:43 AM CDT, BastiaanMDC <notifications@github.com> wrote:




Hi Kris, I am having problems with your library for all other variables it works fine. except mine.

so ill explain. I am getting from MAX31855 values that are double formats and
i am doing the following:

dtostrf(ARRAY_TC_HOT[0],sizeof(ARRAY_TC_HOT[0]),2,str);
Data1.print(str);

screen freezes over.... why is that?

if Serial.println(ARRAY_TC_HOT[0]) I neatly get my temperature value, I dont understand.

i tried this also in combination with the Sprintf command

best regards

Bastiaan

**Comment by BastiaanMDC** [comment]
Hi Kris,

good morning,

I am one step further, after a hint from the Maxim Integrated guys. The MAX31855 needs to be set to SPI_MODE 0.
The PDF_TOTAL is the total schematic how it is wired on the PCB.
The upper left corner shows the DCDC converter,
pins out pump
header to front panel with all the voltages 24,12,5,3.3V with leds, RGB Encoder with a push button which is connected with 4 10K resistors and 2x 10nF caps.
The upper right corner shows all 8 OPA365, voltage follower and amplification from 140mV to 3.3V all calculated and sometimes pulled up by a resistor are read out by the Internal ADC.
The lower right shows the 18V25, VNH5019 Hbridge drivers for 3x Peltier groups of each 16.7A.

so I have followed the manual as https://www.pjrc.com/better-spi-bus-design-in-3-steps/

1.       hooked up the CS Pins with a 4.7K resistor to VCC at the MAX31855

2.       hooked up the MISO line to a voltage divider 10K on the breadboard. Check: no action on the MISO it floats to 1.697V on the oscilloscope, so that’s good.

3.       Changed the SPI settings for the MAX31855 to SPI_MODE 0, with MSBFIRST, the values such as temperatures and words are displayed on the screen but no refresh of the screen.

4.       The CS Pins I am using are: 14,15,16,17 on the Teensy3.6

5.       I am getting getting read out at the serial monitor if both functions are uncommented, and also serial prints at the end of the TFT function that are shown in the Snippet.txt

6.       In total there are 4 functions in void loop():

a.       InternalADC

b.      MenuCheck()

c.       MenuCountdown()

d.      Thermocouple1_4()



7.       The TFT MenuCountdown() program runs parallel to the menuCheck() function. By rotating the knob of the encoder I can change the value , let’s say 0…100 and by clicking again I can go to menu2 3,4, and so on, this is also put on the TFT Screen.

8.       These values are then copied to the same TFT function ( setting the Setpoint of the PID control )//momentarily it is  commented out.


For a Test I checked:  void loop the program Thermocouple1_4(); has been commented out. I get data on the tft screen from the Currents (which is jibberish) because there is not current yet, and the Internal ADC is working in the teensy.

If both programs are run in the void loop I get: a diagnostics check from the Screen that everything is a OK.
The TC0,TC1 and so on are the Internal and External Temperatures from each of the Thermocouples. NOT is not calibrated the max31855 has to undergo a calibration if it goes below Zero.

TC0 pin14 INT 25.88 NOT 23.75

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.31 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

I know this is childsplay for you, but I would like to understand why it isn’t working properly.

Best regards

Bastiaan







_t3n::begin mosi:11 miso:12 SCLK:13 CS:8 DC:10 SPI clocks: 26000000 2000000
_t3n::begin - completed

Display Power Mode: 0xCE

MADCTL Mode: 0xE0

Pixel Format: 0x2

Image Format: 0x0

Self Diagnostic: 0xE0

MENU1 set SampleTime 

0test TC00.00

test TC10.00

test TC20.00

test TC30.00

finished loading all variables

Starting MENU1

TC0 pin14 INT 0.00 NOT 0.00

TC1 pin15 INT 0.00 NOT 0.00

TC2 pin16 INT 26.25 NOT 17.25

TC3 pin17 INT 25.38 NOT 12.50

MENU1 set SampleTime 

test TC00.00

test TC10.00

test TC217.25

test TC312.50

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 23.75

TC1 pin15 INT 26.50 NOT 22.25

TC2 pin16 INT 26.31 NOT 17.25

TC3 pin17 INT 25.38 NOT 12.50

MENU1 set SampleTime 

test TC023.75

test TC122.25

test TC217.25

test TC312.50

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 23.75

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.31 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC023.75

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.44 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 25.00

TC1 pin15 INT 26.44 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.50

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.50

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.50

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.50

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.88 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

finished loading all variables

Starting MENU1

TC0 pin14 INT 25.81 NOT 25.00

TC1 pin15 INT 26.50 NOT 25.75

TC2 pin16 INT 26.25 NOT 25.00

TC3 pin17 INT 25.38 NOT 24.25

MENU1 set SampleTime 

test TC025.00

test TC125.75

test TC225.00

test TC324.25

**Comment by KrisKasprzak** [comment]
The actual issue does not look like it's flickerfree related. If it is, please submit a code example highlighting the problem. From the above post the issue looks like it's related to multiple SPI devices. 

Hence, closing.

**Comment by BastiaanMDC** [comment]
It is related to multiple SPI devices on the bus.

Many thanks for your time and effort!

Closing.



Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Kris Kasprzak <notifications@github.com>
Verzonden: donderdag, september 17, 2020 3:38 PM
Aan: KrisKasprzak/FlickerFreePrint
CC: BastiaanMDC; Author
Onderwerp: [ext] Re: [KrisKasprzak/FlickerFreePrint] questions about flickerfreeprint (#1)


The actual issue does not look like it's flickerfree related. If it is, please submit a code example highlighting the problem. From the above post the issue looks like it's related to multiple SPI devices.

Hence, closing.
