### ISSUE TITLE
Char doesn't seem to be printing correctly.

### ISSUE THREAD

**Issue by jhsa** [KrisKasprzak/FlickerFreePrint#2]
Hi I am trying the code below. It is printing the numbers associated with the text instead of printing the characters. 
Is it not possible to do this, or am I doing something wrong? 
Thank you.

```
char PresetName;

tft.setFont(&FreeMonoBold24pt7b);
      tft.setTextSize(1);
     Data2.setTextColor(ILI9341_BLUE, ILI9341_BLACK);
      SetCursor(16, 32);

      EEread = read_data[(ActiveBank + PresetNumber) + (ActiveBank * 8) + 20];
      PresetNames_read = ((ActiveBank + PresetNumber) + (ActiveBank * 8)) * 8 + 6744;

      for (address = PresetNames_read; address < PresetNames_read + 8; address ++)       // read the characters from preset
      {
        PresetName = read_data[address];
        
        Data2.print(PresetName);
      }

      tft.setFont();
```

**Comment by KrisKasprzak** [comment]
I don't think you can  populate a char that way.

Test it by replacing Data2.print(PresetName); with Serial.println(PresetName);

you must use strcpy, something like this:

char buff[50];
strcpy (buff,PresetName);
Data2.print(buff);

**Comment by jhsa** [comment]
Will try that.. Thank you.
