### ISSUE TITLE
dtostrf 

### ISSUE THREAD

**Issue by DiversSi** [KrisKasprzak/FlickerFreePrint#3]
dtostrf not present in Adafruit library for  M4 or M0 feathers

**Comment by KrisKasprzak** [comment]
Yep, that capability omitted from the default setup. I have added the required lib to this library

You can either
1. re pull this library
2. add the #include <avr/dtostrf.h> to your copy of FlickerFreePrint.h

I can at least compile using this library.

**Comment by DiversSi** [comment]
Yes, that works now. Thanks.
