### ISSUE TITLE
Unable to compile for Arduino Pro 

### ISSUE THREAD

**Issue by Kotik82** [KrisKasprzak/FlickerFreePrint#4]
Hello, getting the following error when trying to compile for pro mini.

#include <avr/dtostrf.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Pro or Pro Mini.

**Comment by KrisKasprzak** [comment]
Just open up the .cpp and .h file and comment that line out

**Comment by Kotik82** [comment]
Thanx that did the trick, i could compile and run the code, but unfortunately i am still getting exactly the same flickering as i had before. Below is my code:

#include <FlickerFreePrint.h>
#include <Arduino_GFX_Library.h>
#include "FreeSansBold8pt7b.h"
#define C_WHITE      0xFFFF
#define C_BLACK      0x0000
Arduino_DataBus *bus = new Arduino_HWSPI(8 /* DC */, 9 /* CS */);
Arduino_GFX *gfx = new Arduino_GC9A01(bus, -1 /* RST */, 0 /* rotation */, true /* IPS */);
FlickerFreePrint<Arduino_GC9A01> Data1(&*gfx, C_WHITE, C_BLACK);

void setup() {
 
    gfx->begin();
    gfx->fillScreen(C_BLACK);
    #ifdef TFT_BL
    pinMode(TFT_BL, OUTPUT);
    digitalWrite(TFT_BL, HIGH);
    #endif
}

void loop() {
  gfx->setCursor(100, 60);
  gfx->setFont(&FreeSansBold8pt7b);
  Data1.setTextColor(C_WHITE, C_BLACK);
  Data1.print(temperature);
}

temperature is an analog reading from a thermistor.

**Comment by KrisKasprzak** [comment]
Put a delay in the loop and see if that helps. Maybe delay(500);

**Comment by Kotik82** [comment]
Hey, thanx for the reply.

I did try with a delay of up to 1500 still same issue, obviously it does it every 1.5 sec instead of constantly.

I had a bit of reading done and i came to the conclusion that the proper solution for this issue is to use a canvas but for that i will need something stronger than Atmega328, with more memory to be able to buffer the canvas.

I am closing this one since it is not an issue with ur code but rather a general issue of fonts in combination with LCD displays.
