### ISSUE TITLE
Error Message for Mega 2560

### ISSUE THREAD

**Issue by Firedogs2x** [KrisKasprzak/FlickerFreePrint#7]
Hello, I am using a Mega 2560 clone.
Along with a Adafruit 2.4 TFT touchscreen (https://www.adafruit.com/product/2478).
I just installed your library.
When I attempt to compile my program, I get the following error.

In file included from C:\Users\AAAA\Documents\Arduino\PID_Temperature_Contoller_Funtioning_Home_Page_Mega\PID_Temperature_Contoller_Funtioning_Home_Page_Mega.ino:1:0:
C:\Users\AAAA\Documents\Arduino\libraries\FlickerFreePrint-master/FlickerFreePrint.h:48:10: fatal error: avr/dtostrf.h: No such file or directory
 #include <avr/dtostrf.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1.

I even redownloaded the zip file and installed it again using Arduino IDE.
Yes, I did try to compile my code after removing your library "#include <FlickerFreePrint.h>". And I was able to run my code with no issues.
Is this library not able to be used with the Mega?

Hopefully with your help I can give your library a try.
Thank you.

**Comment by KrisKasprzak** [comment]
Comment the include statement outThanks.KrisOn Jan 30, 2023, at 10:27 PM, Firedogs2x ***@***.***> wrote:﻿
Hello, I am using a Mega 2560 clone.
Along with a Adafruit 2.4 TFT touchscreen (https://www.adafruit.com/product/2478).
I just installed your library.
When I attempt to compile my program, I get the following error.
In file included from C:\Users\AAAA\Documents\Arduino\PID_Temperature_Contoller_Funtioning_Home_Page_Mega\PID_Temperature_Contoller_Funtioning_Home_Page_Mega.ino:1:0:
C:\Users\AAAA\Documents\Arduino\libraries\FlickerFreePrint-master/FlickerFreePrint.h:48:10: fatal error: avr/dtostrf.h: No such file or directory
#include <avr/dtostrf.h>
^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Compilation error: exit status 1.
I even redownloaded the zip file and installed it again using Arduino IDE.
Yes, I did try to compile my code after removing your library "#include <FlickerFreePrint.h>". And I was able to run my code with no issues.
Is this library not able to be used with the Mega?
Hopefully with your help I can give your library a try.
Thank you.

**Comment by Firedogs2x** [comment]
Hello, thank you for the quick reply.
I did as you told me, I commented out the avr/dtostrf,
My program compiled.
Thank you.
