### ISSUE TITLE
can we do fillRect without that top to bottom render?

### ISSUE THREAD

**Issue by maharzan** [KrisKasprzak/FlickerFreePrint#9]
Like mentioned, is is possible to use this library to to flicker free rectangle? By default, it just paints from top to bottom. I am trying to do blinking red color so one time black and one time red but it renders from top to bottom and it doesn't look smooth.

**Comment by KrisKasprzak** [comment]
Unfortunately, no this is for text only. Depending on what library are using some offer a method to save a rectangle to memory then you can draw that rectangle. I don’t know if it paints top to bottom or how it does it but that might be something to look into.
